package org.jbpt.graph.algo.tctree;
/**
 * @author Martin Mader
 * @author Christian Wiggert
 *
 */
public enum MetaInfo {
	HIDDEN_EDGES,
	ASSIGNED_VIRTUAL_EDGES,
	VIRTUAL_EDGES,
	DFS_ADJ_LISTS,
	DFS_ORDERED_ADJ_LISTS,
	DFS_NUM,
	DFS_COMPL_NUM,
	DFS_NODE_STATE,
	DFS_EDGE_TYPE,
	DFS_LOWPT1_NUM,
	DFS_LOWPT2_NUM,
	DFS_LOWPT1_VERTEX,
	DFS_LOWPT2_VERTEX,
	DFS_HIGHPT_LISTS,
	DFS_NUM_DESC,
	DFS_PARENT,
	DFS_STARTS_NEW_PATH,
	DFS_PATH_NUMBER,
	DFS_NUM_V,
	DFS_NUM_TREE_EDGES,
	DFS_EDGE_COUNT
}
